Revert changes adding empty config dictionary for the Sanitizer API
This breaks the build at the moment with the following error:

  python ../../third_party/blink/renderer/bindings/scripts/idl_compiler.py --cache-dir gen/third_party/blink/renderer/bindings/scripts --output-dir gen/third_party/blink/renderer/bindings/modules/v8 --info-dir gen/third_party/blink/renderer/bindings --target-component modules --read-idl-list-from-file gen/third_party/blink/renderer/bindings/modules/v8/generate_bindings_modules_v8_interfaces_file_list.tmp
  Traceback (most recent call last):
    File "../../third_party/blink/renderer/bindings/scripts/idl_compiler.py", line 201, in <module>
      sys.exit(main())
    File "../../third_party/blink/renderer/bindings/scripts/idl_compiler.py", line 197, in main
      input_filenames)
    File "../../third_party/blink/renderer/bindings/scripts/idl_compiler.py", line 138, in generate_bindings
      idl_compiler.compile_file(idl_filename)
    File "../../third_party/blink/renderer/bindings/scripts/idl_compiler.py", line 125, in compile_file
      self.compile_and_write(idl_filename)
    File "../../third_party/blink/renderer/bindings/scripts/idl_compiler.py", line 111, in compile_and_write
      definitions = self.reader.read_idl_definitions(idl_filename)
    File "/home/mario/work/brave-rebases/brave-browser/src/third_party/blink/renderer/bindings/scripts/idl_reader.py", line 97, in read_idl_definitions
      definitions = self.read_idl_file(idl_filename)
    File "/home/mario/work/brave-rebases/brave-browser/src/third_party/blink/renderer/bindings/scripts/idl_reader.py", line 121, in read_idl_file
      definitions = IdlDefinitions(ast)
    File "/home/mario/work/brave-rebases/brave-browser/src/third_party/blink/renderer/bindings/scripts/idl_definitions.py", line 114, in __init__
      interface = IdlInterface(child)
    File "/home/mario/work/brave-rebases/brave-browser/src/third_party/blink/renderer/bindings/scripts/idl_definitions.py", line 348, in __init__
      attr.idl_type)
  ValueError: Type "SanitizerConfig" cannot be used as an attribute.

commit 428b08c580d7b81a6be4c020cd1b451292617bc5
Author: Yifan Luo <lyf@google.com>
Date:   Fri Sep 11 14:55:03 2020 +0000

    [Sanitizer API] Add empty config dictionary.

    Bug: 1116418